"""empty message

Revision ID: 03c400d739eb
Revises: 56a21d003c74
Create Date: 2022-05-30 17:50:02.241187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c400d739eb'
down_revision = '56a21d003c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('description', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('is_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.add_column('venue', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'created_at')
    op.drop_column('venue', 'genres')
    op.drop_column('venue', 'is_talent')
    op.drop_column('venue', 'description')
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###
