"""empty message

Revision ID: 350fc5f7f3f1
Revises: 03c400d739eb
Create Date: 2022-05-30 17:50:20.918996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350fc5f7f3f1'
down_revision = '03c400d739eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('description', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('is_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'is_venue')
    op.drop_column('artist', 'description')
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
