"""empty message

Revision ID: 35ee8df2afc0
Revises: f34c23c78be8
Create Date: 2022-05-27 17:10:09.965901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ee8df2afc0'
down_revision = 'f34c23c78be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('description', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('is_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'is_venue')
    op.drop_column('artist', 'description')
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
