"""empty message

Revision ID: 675510849be7
Revises: ce2c6d2129e0
Create Date: 2022-05-27 19:28:24.855080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675510849be7'
down_revision = 'ce2c6d2129e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
