"""empty message

Revision ID: ad415ec8143c
Revises: 24642992db52
Create Date: 2022-05-29 14:05:17.470682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad415ec8143c'
down_revision = '24642992db52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('description', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('is_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'is_venue')
    op.drop_column('artist', 'description')
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
